"""
exception, how it works?
"""

def fa():
    fb()

def fb():
    fc()

def fc():
    print(a)



# main program
# call fa()
fa()